[package]
name = "AdventOfCode2024"
version = "0.1.0"
edition = "2021"

[lib]
name = "advent"
path = "lib/mod.rs"

[dependencies]
regex = "1.11.1"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "day_11_benchmark"
harness = false
